# core/intelligence/renderer.py

"""
Project Sentinel

Intelligence Renderer

Responsible for displaying historical analysis generated by
Sentinel Intelligence.

This module performs no analysis.

It only renders intelligence reports.
"""

from textwrap import fill


# ==========================================================
# Constants
# ==========================================================

REPORT_WIDTH = 52
LABEL_WIDTH = 24

LINE = "=" * REPORT_WIDTH

ICONS = {
    "Critical": "✖",
    "Warning": "⚠",
    "Information": "ℹ",
}


# ==========================================================
# Public API
# ==========================================================

def render(report: dict) -> None:
    """
    Render a complete intelligence report.
    """

    print_header()

    if "game" in report:
        print_game(report["game"])

    if "performance" in report:
        print_performance(report["performance"])

    if "cpu" in report:
        print_cpu(report["cpu"])

    if "gpu" in report:
        print_gpu(report["gpu"])

    if "memory" in report:
        print_memory(report["memory"])

    if "recommendations" in report:
        print_recommendations(report["recommendations"])


# ==========================================================
# Header
# ==========================================================

def print_header() -> None:
    """
    Print report header.
    """

    divider()

    print("SENTINEL INTELLIGENCE".center(REPORT_WIDTH))

    divider()
    blank()


# ==========================================================
# Formatting
# ==========================================================

def format_fps(value) -> str:
    """
    Format an FPS value.
    """

    if value is None:
        return "--"

    return f"{round(value)} FPS"


def format_temperature(value) -> str:
    """
    Format a temperature.
    """

    if value is None:
        return "--"

    return f"{value:.1f} °C"


def format_percent(value) -> str:
    """
    Format a percentage.
    """

    if value is None:
        return "--"

    return f"{value:.1f} %"


def truncate(text: str, width: int) -> str:
    """
    Truncate text to a fixed width.
    """

    if len(text) <= width:
        return text

    return text[:width - 3] + "..."


# ==========================================================
# Game
# ==========================================================

def print_game(game: dict) -> None:
    """
    Render selected game summary.
    """

    heading("Game")

    field(
        "Name",
        game.get("name"),
    )

    field(
        "Sessions Recorded",
        game.get("sessions"),
    )

    field(
        "First Session",
        game.get("first_session"),
    )

    field(
        "Latest Session",
        game.get("latest_session"),
    )

    blank()


# ==========================================================
# Performance
# ==========================================================

def print_performance(performance: dict) -> None:
    """
    Render performance statistics.
    """

    heading("Performance")

    field(
        "Average FPS",
        format_fps(performance.get("average_fps")),
    )

    best = performance.get("best_session")

    field(
        "Best Session",
        str(best) if best else "--",
    )

    field(
        "Trend",
        performance.get("trend"),
    )

    print_intelligence(
        performance.get("intelligence", [])
    )

    blank()


# ==========================================================
# CPU
# ==========================================================

def print_cpu(cpu: dict) -> None:
    """
    Render CPU statistics.
    """

    heading("CPU")

    field(
        "Average Temp",
        format_temperature(cpu.get("average_temperature")),
    )

    field(
        "Highest Temp",
        format_temperature(cpu.get("highest_temperature")),
    )

    field(
        "Trend",
        cpu.get("trend"),
    )

    print_intelligence(
        cpu.get("intelligence", [])
    )

    blank()


# ==========================================================
# GPU
# ==========================================================

def print_gpu(gpu: dict) -> None:
    """
    Render GPU statistics.
    """

    heading("GPU")

    field(
        "Average Temp",
        format_temperature(gpu.get("average_temperature")),
    )

    field(
        "Highest Temp",
        format_temperature(gpu.get("highest_temperature")),
    )

    field(
        "Trend",
        gpu.get("trend"),
    )

    print_intelligence(
        gpu.get("intelligence", [])
    )

    blank()


# ==========================================================
# Memory
# ==========================================================

def print_memory(memory: dict) -> None:
    """
    Render memory statistics.
    """

    heading("Memory")

    field(
        "Average Load",
        format_percent(memory.get("average_load")),
    )

    field(
        "Highest Load",
        format_percent(memory.get("highest_load")),
    )

    field(
        "Trend",
        memory.get("trend"),
    )

    print_intelligence(
        memory.get("intelligence", [])
    )

    blank()


# ==========================================================
# Historical Intelligence
# ==========================================================

def print_intelligence(
    statements: list[str],
) -> None:
    """
    Render historical intelligence statements.
    """

    if not statements:
        return

    print("Historical Intelligence")
    print()

    for statement in statements:

        wrapped = fill(
            statement,
            width=REPORT_WIDTH - 4,
            initial_indent="• ",
            subsequent_indent="  ",
        )

        print(wrapped)

    blank()


# ==========================================================
# Recommendations
# ==========================================================

def print_recommendations(
    recommendations: list[dict],
) -> None:
    """
    Render Sentinel recommendations.
    """

    heading("Recommendations")

    if not recommendations:

        print("No recommendations.")
        blank()
        return

    for recommendation in recommendations:

        level = recommendation.get("level", "")
        title = recommendation.get("title", "")
        message = recommendation.get("message", "")

        icon = ICONS.get(level, "•")

        print(f"{icon} {title}")
        print()

        wrapped = fill(
            message,
            width=REPORT_WIDTH - 4,
            initial_indent="    ",
            subsequent_indent="    ",
        )

        print(wrapped)
        print()

    blank()


# ==========================================================
# Helpers
# ==========================================================

def heading(title: str) -> None:
    """
    Print a section heading.
    """

    divider()
    print(title)
    divider()
    blank()


def field(
    label: str,
    value,
) -> None:
    """
    Print an aligned label/value pair.
    """

    if value is None:
        value = "--"

    print(f"{label:<{LABEL_WIDTH}} {value}")


def divider() -> None:
    """
    Print divider.
    """

    print(LINE)


def blank() -> None:
    """
    Print blank line.
    """

    print()