# core/intelligence/renderer.py

"""
Project Sentinel

Intelligence Renderer

Responsible for displaying historical analysis generated by
Sentinel Intelligence.

This module performs no analysis.

It only renders intelligence reports.
"""

from textwrap import fill


# ==========================================================
# Constants
# ==========================================================

REPORT_WIDTH = 52
LABEL_WIDTH = 24

LINE = "=" * REPORT_WIDTH

ICONS = {
    "Critical": "✖",
    "Warning": "⚠",
    "Information": "ℹ",
}


# ==========================================================
# Public API
# ==========================================================

def render(report: dict) -> None:
    """
    Render a complete intelligence report.
    """

    print_header()

    if "game" in report:
        print_game(report["game"])

    if "performance" in report:
        print_performance(report["performance"])

    if "cpu" in report:
        print_cpu(report["cpu"])

    if "gpu" in report:
        print_gpu(report["gpu"])

    if "memory" in report:
        print_memory(report["memory"])

    if "recommendations" in report:
        print_recommendations(report["recommendations"])


# ==========================================================
# Header
# ==========================================================

def print_header() -> None:
    divider()
    print("SENTINEL INTELLIGENCE".center(REPORT_WIDTH))
    divider()
    blank()


# ==========================================================
# Safe formatting helpers (NEW)
# ==========================================================

def format_session(session) -> str:
    """
    Convert session objects/dicts into display string.
    """

    if session is None:
        return "--"

    if isinstance(session, dict):
        return session.get("display_name") or f"{session.get('game')} Session"

    return str(session)


def format_fps(value):
    if value is None:
        return "--"
    return f"{round(value)} FPS"


def format_temperature(value):
    if value is None:
        return "--"
    return f"{value:.1f} °C"


def format_percent(value):
    if value is None:
        return "--"
    return f"{value:.1f} %"


def truncate(text: str, width: int) -> str:
    if not isinstance(text, str):
        text = str(text)

    if len(text) <= width:
        return text

    return text[:width - 3] + "..."


# ==========================================================
# Game
# ==========================================================

def print_game(game: dict) -> None:
    heading("Game")

    field("Name", game.get("name"))
    field("Sessions Recorded", game.get("sessions"))

    field(
        "First Session",
        format_session(game.get("first_session")),
    )

    field(
        "Latest Session",
        format_session(game.get("latest_session")),
    )

    blank()


# ==========================================================
# Performance
# ==========================================================

def print_performance(performance: dict) -> None:
    heading("Performance")

    field(
        "Average FPS",
        format_fps(performance.get("average_fps")),
    )

    best = performance.get("best_session")

    field(
        "Best Session",
        format_session(best),
    )

    field("Trend", performance.get("trend"))

    print_intelligence(performance.get("intelligence", []))
    blank()


# ==========================================================
# CPU
# ==========================================================

def print_cpu(cpu: dict) -> None:
    heading("CPU")

    field(
        "Average Temp",
        format_temperature(cpu.get("average_temperature")),
    )

    field(
        "Highest Temp",
        format_temperature(cpu.get("highest_temperature")),
    )

    field("Trend", cpu.get("trend"))

    print_intelligence(cpu.get("intelligence", []))
    blank()


# ==========================================================
# GPU
# ==========================================================

def print_gpu(gpu: dict) -> None:
    heading("GPU")

    field(
        "Average Temp",
        format_temperature(gpu.get("average_temperature")),
    )

    field(
        "Highest Temp",
        format_temperature(gpu.get("highest_temperature")),
    )

    field("Trend", gpu.get("trend"))

    print_intelligence(gpu.get("intelligence", []))
    blank()


# ==========================================================
# Memory
# ==========================================================

def print_memory(memory: dict) -> None:
    heading("Memory")

    field(
        "Average Load",
        format_percent(memory.get("average_load")),
    )

    field(
        "Highest Load",
        format_percent(memory.get("highest_load")),
    )

    field("Trend", memory.get("trend"))

    print_intelligence(memory.get("intelligence", []))
    blank()


# ==========================================================
# Intelligence
# ==========================================================

def print_intelligence(statements: list[str]) -> None:
    if not statements:
        return

    print("Historical Intelligence")
    print()

    for statement in statements:
        wrapped = fill(
            statement,
            width=REPORT_WIDTH - 4,
            initial_indent="• ",
            subsequent_indent="  ",
        )
        print(wrapped)

    blank()


# ==========================================================
# Recommendations
# ==========================================================

def print_recommendations(recommendations: list[dict]) -> None:
    heading("Recommendations")

    if not recommendations:
        print("No recommendations.")
        blank()
        return

    for rec in recommendations:

        level = rec.get("level", "")
        title = rec.get("title", "")
        message = rec.get("message", "")

        icon = ICONS.get(level, "•")

        print(f"{icon} {title}")
        print()

        wrapped = fill(
            message,
            width=REPORT_WIDTH - 4,
            initial_indent="    ",
            subsequent_indent="    ",
        )

        print(wrapped)
        print()

    blank()


# ==========================================================
# Helpers
# ==========================================================

def heading(title: str) -> None:
    divider()
    print(title)
    divider()
    blank()


def field(label: str, value) -> None:
    if value is None:
        value = "--"

    print(f"{label:<{LABEL_WIDTH}} {value}")


def divider() -> None:
    print(LINE)


def blank() -> None:
    print()